- p2p/README.md
- rdma/README.md
- rdma/util_rdma.cc
NCCL_IB_HCA and NCCL_SOCKET_IFNAME are also supported.
> UCCL_IB_HCA, UCCL_SOCKET_IFNAME

- efa/eqds.cc
- efa/eqds.h
This fixes https://github.com/uccl-project/uccl/issues/110
> fixing build bugs

- .gitignore
- docker_build.sh
- rdma/README.md
- rdma/rdma_io.cc
- rdma/rdma_io.h
- rdma/run_rccl_test.sh
- rdma/run_rccl_test_hpcfund.sh
- rdma/transport_config.h
Adding dummy ex_cq creation in RDMAFactory::init_devs().
> removing Macro of BROADCOM_NIC

- p2p/README.md
- p2p/benchmarks/benchmark.py
- p2p/engine.cc
- p2p/engine.h
- p2p/pybind_engine.cc
For now, we assume the receiver side knows the exact bytes to receive in advance.
> add async transfer for p2p

- p2p/README.md
- p2p/benchmarks/benchmark_uccl.py
- p2p/benchmarks/benchmark_uccl_dual.py
- rdma/transport.cc
- rdma/util_rdma.h
Unrelated to these changes, I find sometimes the p2p server side will trigger errors: 
@zhongjiechen @MaoZiming any thoughts?
> GPU p2p on gh200 now works using ibv_reg_mr_iova2

- gpu_driven/Makefile
- gpu_driven/bench/test_internode_simple.py
- gpu_driven/bench/utils.py
- gpu_driven/src/uccl_ep.cc
- include/util/util.h
- setup.py
* Adding a dummy Python wrapper for `low_latency_dispatch` and `low_latency_combine`
* To test: `test_internode_simple.py`.
> Gpu driven support dispatch and combine

- .vscode/c_cpp_properties.json
- build.sh
- docker/Dockerfile.gh
- gpu_driven/Makefile
- gpu_driven/bench/buffer.py
- gpu_driven/bench/test_internode_simple.py
- gpu_driven/bench/utils.py
- gpu_driven/include/ep_util.hpp
- gpu_driven/src/uccl_ep.cc
- thirdparty/DeepEP/deep_ep/utils.py
* `uccl_ep.cc` mirrors `deep_ep.cc`
* Adding `buffer.py`, similar to `buffer.py` in `thirdparty/DeepEP/deep_ep/buffer.py`.
* Added Torch dependencies in Docker file.
> Add `buffer.py` and bring torch to uccl_ep.cc

- gpu_driven/Makefile
- gpu_driven/bench/buffer.py
- gpu_driven/include/ep_config.hpp
- gpu_driven/include/ep_util.hpp
- gpu_driven/include/internode_ll.cuh
- gpu_driven/src/internode_ll.cu
- gpu_driven/src/uccl_ep.cc
Added template functions:
* dispatch
* combine
* init
* alloc
* barrier
* get_unique_id
> Adding `internode_ll.cu` to UCCL

- gpu_driven/bench/buffer.py
- gpu_driven/bench/test_internode_simple.py
- gpu_driven/include/ep_config.hpp
- gpu_driven/src/ep_runtime.cpp
- gpu_driven/src/internode_ll.cu
- gpu_driven/src/uccl_ep.cc
* Adding `struct LowLatencyBuffer` in `ep_config.hpp`. 
* Comment out `nvshmem` code.
* Other minor fixes.
> [gpu_driven] Fix LowLatencyBuffer and workspace_

- gpu_driven/include/proxy_ctx.hpp
- gpu_driven/src/peer_copy_worker.cpp
- gpu_driven/src/proxy.cpp
Previous merge conflict has some compilation issue.
> [GPU-driven] Clean merge compile issues

- .github/workflows/remote-uccl-build.yml
- docker/Dockerfile.cuda
Add build integration test for UCCL.
> UCCL build integration test

- .github/workflows/remote-uccl-build.yml
- docker/Dockerfile.cuda
> Build integration test

- gpu_driven/bench/test_internode_simple.py
- gpu_driven/src/internode_ll.cu
- gpu_driven/src/uccl_ep.cc
* Due to merge conflict, there was still `sizeof(uint64_t)`, removed in this PR.
> GPU driven offset fix

- .github/workflows/remote-uccl-build.yml
> Update workflow to remove pull request trigger

- ep/src/rdma.cpp
Committer: YangZhou1997 <yangzhou.rpc@gmail.com>
> fixing rdma finding bug

- ep/README.md
Updated the README to reflect the new name and added details about running DeepEP-style dispatch tests.
> Updated the README to reflect the new folder name and added details about running DeepEP-style dispatch tests.

- README.md
- build.sh
- build_and_install.sh
> add target for build

- ep/bench/utils.py
- ep/src/internode_ll.cu
https://github.com/uccl-project/uccl/pull/367#issuecomment-3289903210
> EP: fix uint8 numeric problem.

- README.md
- ep/src/internode_ll.cu
> Enrich readme with collectives, p2p, and ep

- ep/bench/utils.py
This problem was fixed on DeepEP repo too: 
[https://github.com/deepseek-ai/DeepEP/commit/c5facf5c6fef042e56627c33817feebaf97aee26#diff-9e08e8c7769db7b58089fd76[…]b7b5d50299d3a30abd54da9ad6R174](https://github.com/deepseek-ai/DeepEP/commit/c5facf5c6fef042e56627c33817feebaf97aee26#diff-9e08e8c7769db7b58089fd7659d75ca96df40bb7b5d50299d3a30abd54da9ad6R174)
> EP Fix bench kineto

- doc/dev_rdma.md
> quick fix on AMD build

- README.md
- build_and_install.sh
> quick fix on amd readme

- ep/bench/benchmark_dual.cu
- ep/bench/benchmark_remote.py
- ep/bench/test_ipc_ptr_logic.py
- ep/bench/test_p2p_simple.py
- ep/bench/utils.py
- ep/include/bench_utils.hpp
- ep/include/proxy.hpp
- ep/include/rdma.hpp
- ep/include/uccl_proxy.hpp
- ep/src/proxy.cpp
- ep/src/rdma.cpp
- ep/src/uccl_ep.cc
- ep/src/uccl_proxy.cpp
- ep/tests/batched_gpu_to_cpu_bench.cu
- ep/tests/test_local_proxy.py
> EP: rename block_idx to thread_idx

- ep/README.md
- ep/include/common.hpp
- ep/src/rdma.cpp
- include/util/util.h
* Main issue is that the current NIC selection checks all equal-distance NIC, didn't check whether a NIC is up or down. 
* Added `uccl::is_iface_up` during NIC selection.. 
> EP: Fix GH200 & automatically detecting down NIC

- README.md
> fixing cite in readme

- p2p/README.md
- p2p/benchmarks/benchmark_uccl.py
- p2p/benchmarks/benchmark_uccl_read.py
- p2p/benchmarks/benchmark_uccl_write.py
> fixing benchmark_uccl_read/write error 12

- ep/include/common.hpp
- ep/include/proxy.hpp
- ep/include/proxy_ctx.hpp
- ep/src/common.cpp
- ep/src/proxy.cpp
- ep/src/rdma.cpp
> add pin numa to avoid pin cpu that might suffer from core contention
